name: Lint
on: 
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]
jobs:
  read-data:
    name: "Read data"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v2
      - name: "Read"
        run: cat hello.txt 
